package rules.xuhui
import com.shenzhijie.loguserinfo.web.base.entity.ShenTestTable
import com.shenzhijie.loguserinfo.web.base.entity.rulePojo.DroolsPojo

/*全局变量*/
global java.util.Map mapResult;

 rule "Boardten"
salience 10
 when
     $ShenTestTable:ShenTestTable(boardId == 10)
  then
     System.out.println("boardId为:"+$ShenTestTable.getBoardId());
     mapResult.put("board1","10");
  end

 rule "BoardHundred"
salience 9
 when
     $ShenTestTable:ShenTestTable(boardId == 100)
  then
     System.out.println("boardId为:"+$ShenTestTable.getBoardId());
     mapResult.put("board2","100");
  end


   rule "BoardThousand"
    salience 8
   when
       $drools:DroolsPojo(name in ("jay","bom"))
    then
       System.out.println("DroolsPojo.name为:"+$drools.getName());
       mapResult.put("name","jay");
       System.out.println(mapResult.get("name"));
//       update($map) /*更新规则之后执行*/
    end

rule "BoardUndefind"
salience 7
when
  $ShenTestTable:ShenTestTable(boardId != 1000)
then
    System.out.println("未知boardId为:"+$ShenTestTable.getBoardId());
    mapResult.put("board4","bzd");
end

rule "lala"
salience 999
when
    eval(true)
then
    System.out.println("==============无论如何都打印的规则====================");
    mapResult.put("always","zero");
    System.out.println(mapResult.get("always"));
end